# Generated by Django 5.1.6 on 2025-03-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrips', '0002_remove_carphoto_user_remove_documentphoto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentphoto',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_photos', to='autotrips.acceptencereport'),
        ),
    ]
