# Generated by Django 5.1.7 on 2025-05-18 07:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0003_alter_documentphoto_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_type", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "vin",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid vin format.",
                                regex=re.compile("^[A-HJ-NPR-Z0-9]{17}$"),
                            )
                        ],
                    ),
                ),
                ("container_number", models.CharField(max_length=100)),
                ("arrival_date", models.DateField()),
                ("transporter", models.CharField(max_length=100)),
                ("recipient", models.CharField(max_length=100)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Новый", "New")], default="Новый", max_length=10
                    ),
                ),
                (
                    "status_changed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "v_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vehicles",
                        to="autotrips.vehicletype",
                    ),
                ),
            ],
        ),
    ]
