# Generated by Django 5.1.7 on 2025-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0004_vehicletype_vehicleinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_inspector",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_logistician",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_re_export",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="approved_by_title",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="inspection_done",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("required_inspection", "Required Inspection"),
                    ("required_expertise", "Required Expertise"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="inspection_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="inspector_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="logistician_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="manager_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="notified_inspector",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="notified_parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="number_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="number_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="openning_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="requested_title",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="title_collection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="took_title",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("consignment", "Consignment")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="transit_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("t1", "T1"),
                    ("re_export", "Re Export"),
                    ("without_openning", "Without Openning"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="transit_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("loading", "Loading"),
                    ("ready_for_transport", "Ready For Transport"),
                    ("requires_approval", "Requires Approval"),
                    ("rejected", "Rejected"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
    ]
