# Generated by Django 5.1.7 on 2025-08-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0006_vehicleinfo_notified_logistician_by_inspector_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acceptencereport",
            name="model",
        ),
        migrations.RemoveField(
            model_name="acceptencereport",
            name="vin",
        ),
        migrations.AddField(
            model_name="acceptencereport",
            name="vehicle",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="autotrips.vehicleinfo",
            ),
            preserve_default=False,
        ),
    ]
