# Generated by Django 5.1.7 on 2025-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0007_remove_acceptencereport_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinfo",
            name="export",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="prepared_documents",
            field=models.BooleanField(default=False),
        ),
    ]
