# Generated by Django 5.1.7 on 2025-08-16 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0008_vehicleinfo_export_vehicleinfo_prepared_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTransporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="logistician_keys_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="ready_for_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="vehicle_transporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="autotrips.vehicletransporter",
            ),
        ),
    ]
