# Generated by Django 5.1.7 on 2025-08-17 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0009_vehicletransporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinfo",
            name="full_acceptance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="receive_documents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="receive_vehicle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="receiver_keys_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="vehicle_arrival_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
