# Generated by Django 5.1.7 on 2025-08-24 13:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0010_vehicleinfo_full_acceptance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptencereport",
            name="acceptance_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Acceptance date"
            ),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="comment",
            field=models.CharField(max_length=255, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="place",
            field=models.CharField(max_length=100, verbose_name="Place"),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="report_number",
            field=models.IntegerField(default=1, verbose_name="Report number"),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="report_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report time"
            ),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reporter",
            ),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="status",
            field=models.CharField(
                choices=[("Принят", "Accepted"), ("Повреждён", "Damaged")],
                default="Принят",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="autotrips.vehicleinfo",
                verbose_name="Vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="carphoto",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="carphoto",
            name="image",
            field=models.ImageField(upload_to="cars/%Y/%m/%d/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="carphoto",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_photos",
                to="autotrips.acceptencereport",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="documentphoto",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="documentphoto",
            name="image",
            field=models.ImageField(
                upload_to="car-docs/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="documentphoto",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_photos",
                to="autotrips.acceptencereport",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="keyphoto",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="keyphoto",
            name="image",
            field=models.ImageField(upload_to="keys/%Y/%m/%d/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="keyphoto",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_photos",
                to="autotrips.acceptencereport",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_inspector",
            field=models.BooleanField(
                default=False, verbose_name="Approved by inspector"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_logistician",
            field=models.BooleanField(
                default=False, verbose_name="Approved by logistician"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_manager",
            field=models.BooleanField(
                default=False, verbose_name="Approved by manager"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_re_export",
            field=models.BooleanField(
                default=False, verbose_name="Approved by re-export"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_receiver",
            field=models.BooleanField(
                default=False, verbose_name="Approved by receiver"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="approved_by_title",
            field=models.BooleanField(default=False, verbose_name="Approved by title"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="arrival_date",
            field=models.DateField(verbose_name="Arrival date"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Brand"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="container_number",
            field=models.CharField(max_length=100, verbose_name="Container number"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="creation_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation time"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="export",
            field=models.BooleanField(default=False, verbose_name="Export"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="full_acceptance",
            field=models.BooleanField(default=False, verbose_name="Full acceptance"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="inspection_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inspection date"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="inspection_done",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("required_inspection", "Required inspection"),
                    ("required_expertise", "Required expertise"),
                ],
                max_length=20,
                null=True,
                verbose_name="Inspection done",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="inspection_paid",
            field=models.BooleanField(default=False, verbose_name="Inspection paid"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="inspector_comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Inspector comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="logistician_comment",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Logistician comment",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="logistician_keys_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Logistician keys number",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="manager_comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Manager comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="notified_inspector",
            field=models.BooleanField(default=False, verbose_name="Notified inspector"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="notified_logistician_by_inspector",
            field=models.BooleanField(
                default=False, verbose_name="Notified logistician by inspector"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="notified_logistician_by_title",
            field=models.BooleanField(
                default=False, verbose_name="Notified logistician by title"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="notified_parking",
            field=models.BooleanField(default=False, verbose_name="Notified parking"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="number_sent",
            field=models.BooleanField(default=False, verbose_name="Number sent"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="number_sent_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Number sent date"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="opened",
            field=models.BooleanField(default=False, verbose_name="Opened"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="openning_date",
            field=models.DateField(blank=True, null=True, verbose_name="Opening date"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="pickup_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pickup address"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="prepared_documents",
            field=models.BooleanField(default=False, verbose_name="Prepared documents"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="ready_for_receiver",
            field=models.BooleanField(default=False, verbose_name="Ready for receiver"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="receive_documents",
            field=models.BooleanField(default=False, verbose_name="Receive documents"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="receive_vehicle",
            field=models.BooleanField(default=False, verbose_name="Receive vehicle"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="receiver_keys_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Receiver keys number",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="recipient",
            field=models.CharField(max_length=100, verbose_name="Recipient"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="requested_title",
            field=models.BooleanField(default=False, verbose_name="Requested title"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("loading", "Loading"),
                    ("ready_for_transport", "Ready for Transport"),
                    ("requires_approval", "Requires Approval"),
                    ("rejected", "Rejected"),
                ],
                default="initial",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="status_changed",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Status changed"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="title_collection_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Title collection date"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="took_title",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("consignment", "Consignment")],
                max_length=20,
                null=True,
                verbose_name="Took title",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transit_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("t1", "T1"),
                    ("re_export", "Re-Export"),
                    ("without_openning", "Without opening"),
                ],
                max_length=20,
                null=True,
                verbose_name="Transit method",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transit_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Transit number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transporter",
            field=models.CharField(max_length=100, verbose_name="Transporter"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="v_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="vehicles",
                to="autotrips.vehicletype",
                verbose_name="Vehicle type",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="vehicle_arrival_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vehicle arrival date"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="vehicle_transporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="autotrips.vehicletransporter",
                verbose_name="Vehicle transporter",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="vin",
            field=models.CharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid vin format.",
                        regex=re.compile("^[A-HJ-NPR-Z0-9]{17}$"),
                    )
                ],
                verbose_name="VIN",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransporter",
            name="number",
            field=models.CharField(max_length=10, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="v_type",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Vehicle type"
            ),
        ),
    ]
