# Generated by Django 5.1.7 on 2025-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0011_alter_acceptencereport_acceptance_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acceptencereport",
            options={
                "verbose_name": "Acceptance report",
                "verbose_name_plural": "Acceptance reports",
            },
        ),
        migrations.AlterModelOptions(
            name="carphoto",
            options={"verbose_name": "Car photo", "verbose_name_plural": "Car photos"},
        ),
        migrations.AlterModelOptions(
            name="documentphoto",
            options={
                "verbose_name": "Vehicle document photo",
                "verbose_name_plural": "Vehicle document photos",
            },
        ),
        migrations.AlterModelOptions(
            name="keyphoto",
            options={"verbose_name": "Key photo", "verbose_name_plural": "Key photos"},
        ),
        migrations.AlterModelOptions(
            name="vehicleinfo",
            options={
                "verbose_name": "Vehicle info",
                "verbose_name_plural": "Vehicle infos",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletransporter",
            options={
                "verbose_name": "Vehicle transporter",
                "verbose_name_plural": "Vehicle transporters",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletype",
            options={
                "verbose_name": "Vehicle type",
                "verbose_name_plural": "Vehicle types",
            },
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="acceptance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("with_re_export", "With re-export"),
                    ("without_re_export", "Without re-export"),
                ],
                max_length=20,
                null=True,
                verbose_name="Acceptance type",
            ),
        ),
    ]
