# Generated by Django 5.1.7 on 2025-09-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0012_alter_acceptencereport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleinfo",
            name="notified_logistician_by_inspector",
        ),
        migrations.RemoveField(
            model_name="vehicleinfo",
            name="notified_logistician_by_title",
        ),
    ]
