# Generated by Django 5.1.7 on 2025-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autotrips",
            "0013_remove_vehicleinfo_notified_logistician_by_inspector_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinfo",
            name="vin",
            field=models.CharField(unique=True, verbose_name="VIN"),
        ),
    ]
