# Generated by Django 5.1.7 on 2025-12-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0014_alter_vehicleinfo_vin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleinfo",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="vehicleinfo",
            name="model",
        ),
        migrations.AddField(
            model_name="vehicleinfo",
            name="year_brand_model",
            field=models.CharField(
                default=2025, max_length=200, verbose_name="Year brand model"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="acceptencereport",
            name="place",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Place"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="acceptance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("with_re_export", "With re-export"),
                    ("without_re_export", "Without re-export"),
                ],
                default="",
                max_length=20,
                verbose_name="Acceptance type",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="arrival_date",
            field=models.DateField(blank=True, null=True, verbose_name="Arrival date"),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="container_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Container number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="inspector_comment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Inspector comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="logistician_comment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Logistician comment",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="manager_comment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Manager comment"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="pickup_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Pickup address"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="recipient",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Recipient"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="took_title",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("consignment", "Consignment")],
                default="",
                max_length=20,
                verbose_name="Took title",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transit_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("t1", "T1"),
                    ("re_export", "Re-Export"),
                    ("without_openning", "Without opening"),
                ],
                default="",
                max_length=20,
                verbose_name="Transit method",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transit_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Transit number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="transporter",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Transporter"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinfo",
            name="v_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="vehicles",
                to="autotrips.vehicletype",
                verbose_name="Vehicle type",
            ),
        ),
    ]
