# Generated by Django 5.1.7 on 2025-12-10 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autotrips",
            "0015_remove_vehicleinfo_brand_remove_vehicleinfo_model_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDocumentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="vehicle-docs/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_photos",
                        to="autotrips.vehicleinfo",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle document photo",
                "verbose_name_plural": "Vehicle document photos",
            },
        ),
    ]
