# Generated by Django 5.1.7 on 2025-12-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotrips", "0016_vehicledocumentphoto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicledocumentphoto",
            options={
                "verbose_name": "Vehicle info document photo",
                "verbose_name_plural": "Vehicle info document photos",
            },
        ),
        migrations.AlterField(
            model_name="vehicledocumentphoto",
            name="image",
            field=models.ImageField(
                upload_to="info-docs/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
    ]
