# Generated by Django 5.1.6 on 2025-03-18 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentimage",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ] 