# Generated by Django 5.1.7 on 2025-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_documentimage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
