# Generated by Django 5.1.7 on 2025-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("user", "User"),
                    ("client", "Client"),
                    ("logistician", "Logistician"),
                    ("opening_manager", "Opening Manager"),
                    ("title", "Title"),
                    ("inspector", "Inspector"),
                    ("re_export", "Re Export"),
                ],
                default="user",
                max_length=15,
            ),
        ),
    ]
