# Generated by Django 5.1.7 on 2025-09-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_documentimage_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentimage",
            options={
                "verbose_name": "Document photo",
                "verbose_name_plural": "Documents photos",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
