name: Check Application

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
      
      - name: Run Ruff
        run: poetry run ruff check .
      
      - name: Run mypy
        run: poetry run mypy .
  check:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ needs.lint.result == 'success' }}
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: testautotrips
          POSTGRES_USER: testautotrips
          POSTGRES_PASSWORD: testautotrips
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install Poetry
        run: pip install poetry

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=testautotrips" > .env
          echo "DATABASE_USER=testautotrips" >> .env
          echo "DATABASE_PASSWORD=testautotrips" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=5432" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_GROUP_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "SECRET_KEY=testautotrips" >> .env
          echo "TABLE_ID=${{ secrets.TABLE_ID }}" >> .env
          echo "TABLE_CREDS=credentials.json" >> .env
          echo "VINS_WORKSHEET=testvins" >> .env
          echo "CHECKERS_WORKSHEET=testcheck" >> .env
          echo "REPORTS_WORKSHEET=testreport" >> .env
          echo "CLIENTS_WORKSHEET=testclient" >> .env
          echo "VEHICLES_WORKSHEET=testvehicle" >> .env
          echo "FRONTEND_URL=http://localhost:3000/" >> .env
          echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
          echo "DEBUG=True" >> .env
          echo "ADMIN_FULLNAME=test" >> .env
          echo "ADMIN_PHONE=+999999999" >> .env
          echo "ADMIN_TELEGRAM=testautotrips" >> .env
          echo "ADMIN_PASSWORD=testautotrips" >> .env

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: poetry run python src/manage.py migrate

      - name: Run application
        run: poetry run python src/manage.py runserver 0.0.0.0:8000 &
        env:
          DATABASE_URL: postgres://testautotrips:testautotrips@localhost:5432/testautotrips

      - name: Wait for application to start
        run: |
          timeout 120 bash -c 'until curl -s http://localhost:8000 > /dev/null; do sleep 1; done'

      - name: Check application status
        run: |
          curl -I http://localhost:8000